// Generated by gonvex dev. Do not edit.

export const schema = {
  scope: "tenant",
  tables: {
    skill_api_keys: {
      columns: {
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
        key_hash: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        name: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        prefix: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        revoked_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
      },
      indexes: {
        by_key_hash: {
          columns: ["key_hash"],
          unique: false,
        },
      },
    },
    skill_credentials: {
      columns: {
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
        name: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        secret_value: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        summary: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        updated_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
      },
      indexes: {
        by_name: {
          columns: ["name"],
          unique: false,
        },
      },
    },
    skill_sessions: {
      columns: {
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        expires_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
        revoked_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        token_hash: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
      },
      indexes: {
        by_token_hash: {
          columns: ["token_hash"],
          unique: false,
        },
      },
    },
    skills: {
      columns: {
        content: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
        name: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        summary: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        updated_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
      },
      indexes: {
        by_name: {
          columns: ["name"],
          unique: false,
        },
        by_updated_at: {
          columns: ["updated_at"],
          unique: false,
        },
      },
    },
  },
} as const;

export const tables = schema.tables;

export type TableName = keyof typeof tables;
