// Generated by gonvex dev. Do not edit.

export const scope = "tenant" as const;

export const tables = {
  skill_api_keys: {
    columns: {
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      created_by: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      expires_at: {
        nullable: true,
        primaryKey: false,
        type: "time",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      key_hash: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      name: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      owner_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      prefix: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      revoked_at: {
        nullable: true,
        primaryKey: false,
        type: "time",
      },
      scopes: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
    },
    indexes: {
      by_key_hash: {
        columns: ["key_hash"],
        unique: false,
      },
      by_owner_created_at: {
        columns: ["owner_id","created_at"],
        unique: false,
      },
    },
  },
  skill_credentials: {
    columns: {
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      name: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      owner_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      secret_value: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      summary: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      updated_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
    },
    indexes: {
      by_owner_name: {
        columns: ["owner_id","name"],
        unique: false,
      },
    },
  },
  skill_sessions: {
    columns: {
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      expires_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      owner_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      pending_only: {
        nullable: false,
        primaryKey: false,
        type: "bool",
      },
      revoked_at: {
        nullable: true,
        primaryKey: false,
        type: "time",
      },
      token_hash: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      workspace_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
    },
    indexes: {
      by_owner_token_hash: {
        columns: ["owner_id","token_hash"],
        unique: false,
      },
      by_token_hash: {
        columns: ["token_hash"],
        unique: false,
      },
    },
  },
  skill_users: {
    columns: {
      can_own: {
        nullable: false,
        primaryKey: false,
        type: "bool",
      },
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      email: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      name: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      owner_id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      updated_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
    },
    indexes: {
      by_email: {
        columns: ["email"],
        unique: false,
      },
    },
  },
  skill_workspace_invitations: {
    columns: {
      accepted_at: {
        nullable: true,
        primaryKey: false,
        type: "time",
      },
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      email: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      invited_by: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      rejected_at: {
        nullable: true,
        primaryKey: false,
        type: "time",
      },
      workspace_owner_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
    },
    indexes: {
      by_email: {
        columns: ["email"],
        unique: false,
      },
      by_workspace_email: {
        columns: ["workspace_owner_id","email"],
        unique: false,
      },
    },
  },
  skill_workspace_members: {
    columns: {
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      email: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      invited_by: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      workspace_owner_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
    },
    indexes: {
      by_email: {
        columns: ["email"],
        unique: false,
      },
      by_workspace_email: {
        columns: ["workspace_owner_id","email"],
        unique: false,
      },
    },
  },
  skills: {
    columns: {
      approved_at: {
        nullable: true,
        primaryKey: false,
        type: "time",
      },
      approved_by: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      content: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      content_hash: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
      name: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      owner_id: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      summary: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      updated_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
    },
    indexes: {
      by_owner_name: {
        columns: ["owner_id","name"],
        unique: false,
      },
      by_owner_updated_at: {
        columns: ["owner_id","updated_at"],
        unique: false,
      },
    },
  },
} as const;

export type TableName = keyof typeof tables;
