// Generated by gonvex dev. Do not edit.
export const tables = {
  "skill_api_keys": {
    "columns": {
      "created_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "id": {
        "type": "id",
        "nullable": false,
        "primaryKey": true
      },
      "key_hash": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "name": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "owner_id": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "prefix": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "revoked_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      }
    },
    "indexes": {
      "by_key_hash": {
        "columns": [
          "key_hash"
        ],
        "unique": false
      },
      "by_owner_created_at": {
        "columns": [
          "owner_id",
          "created_at"
        ],
        "unique": false
      }
    }
  },
  "skill_credentials": {
    "columns": {
      "created_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "id": {
        "type": "id",
        "nullable": false,
        "primaryKey": true
      },
      "name": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "owner_id": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "secret_value": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "summary": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "updated_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      }
    },
    "indexes": {
      "by_owner_name": {
        "columns": [
          "owner_id",
          "name"
        ],
        "unique": false
      }
    }
  },
  "skill_sessions": {
    "columns": {
      "created_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "expires_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "id": {
        "type": "id",
        "nullable": false,
        "primaryKey": true
      },
      "owner_id": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "revoked_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "token_hash": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "workspace_id": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      }
    },
    "indexes": {
      "by_owner_token_hash": {
        "columns": [
          "owner_id",
          "token_hash"
        ],
        "unique": false
      },
      "by_token_hash": {
        "columns": [
          "token_hash"
        ],
        "unique": false
      }
    }
  },
  "skill_users": {
    "columns": {
      "created_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "email": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "name": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "owner_id": {
        "type": "id",
        "nullable": false,
        "primaryKey": true
      },
      "updated_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      }
    },
    "indexes": {
      "by_email": {
        "columns": [
          "email"
        ],
        "unique": false
      }
    }
  },
  "skill_workspace_members": {
    "columns": {
      "created_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "email": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "id": {
        "type": "id",
        "nullable": false,
        "primaryKey": true
      },
      "invited_by": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "workspace_owner_id": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      }
    },
    "indexes": {
      "by_email": {
        "columns": [
          "email"
        ],
        "unique": false
      },
      "by_workspace_email": {
        "columns": [
          "workspace_owner_id",
          "email"
        ],
        "unique": false
      }
    }
  },
  "skills": {
    "columns": {
      "content": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "created_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      },
      "id": {
        "type": "id",
        "nullable": false,
        "primaryKey": true
      },
      "name": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "owner_id": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "summary": {
        "type": "string",
        "nullable": false,
        "primaryKey": false
      },
      "updated_at": {
        "type": "time",
        "nullable": false,
        "primaryKey": false
      }
    },
    "indexes": {
      "by_owner_name": {
        "columns": [
          "owner_id",
          "name"
        ],
        "unique": false
      },
      "by_owner_updated_at": {
        "columns": [
          "owner_id",
          "updated_at"
        ],
        "unique": false
      }
    }
  }
} as const;
