minimumReleaseAgeExclude:
  - "@gonvex/cli@0.1.31"
  - "@gonvex/client@0.1.31"
  - "@gonvex/protocol@0.1.31"
  - "@gonvex/react@0.1.31"

onlyBuiltDependencies:
  - "@swc/core"

patchedDependencies:
  '@gonvex/cli@0.1.31': patches/@gonvex__cli@0.1.31.patch
