// Generated by gonvex dev. Do not edit.

export const schema = {
  scope: "landlord",
  tables: {
  },
} as const;

export const tables = schema.tables;

export type TableName = keyof typeof tables;
