// Generated by gonvex dev. Do not edit.

export const api = {
  "agent.apiKeys.create": { kind: "mutation", path: "agent.apiKeys.create" },
  "agent.apiKeys.list": { kind: "query", path: "agent.apiKeys.list" },
  "agent.apiKeys.revoke": { kind: "mutation", path: "agent.apiKeys.revoke" },
  "agent.credentials.delete": { kind: "mutation", path: "agent.credentials.delete" },
  "agent.credentials.get": { kind: "query", path: "agent.credentials.get" },
  "agent.credentials.list": { kind: "query", path: "agent.credentials.list" },
  "agent.credentials.save": { kind: "mutation", path: "agent.credentials.save" },
  "agent.skills.delete": { kind: "mutation", path: "agent.skills.delete" },
  "agent.skills.get": { kind: "query", path: "agent.skills.get" },
  "agent.skills.list": { kind: "query", path: "agent.skills.list" },
  "agent.skills.upload": { kind: "mutation", path: "agent.skills.upload" },
  "apiKeys.create": { kind: "mutation", path: "apiKeys.create" },
  "apiKeys.list": { kind: "query", path: "apiKeys.list" },
  "apiKeys.revoke": { kind: "mutation", path: "apiKeys.revoke" },
  "auth.login": { kind: "mutation", path: "auth.login" },
  "auth.logout": { kind: "mutation", path: "auth.logout" },
  "credentials.delete": { kind: "mutation", path: "credentials.delete" },
  "credentials.get": { kind: "mutation", path: "credentials.get" },
  "credentials.list": { kind: "query", path: "credentials.list" },
  "credentials.save": { kind: "mutation", path: "credentials.save" },
  "skills.delete": { kind: "mutation", path: "skills.delete" },
  "skills.list": { kind: "query", path: "skills.list" },
  "skills.save": { kind: "mutation", path: "skills.save" },
} as const;

export type Api = typeof api;
