// Generated by gonvex dev. Do not edit.

export const api = {
  agent: {
    apiKeys: {
      create: { kind: "mutation", path: "agent.apiKeys.create" },
      list: { kind: "query", path: "agent.apiKeys.list" },
      revoke: { kind: "mutation", path: "agent.apiKeys.revoke" },
    },
    credentials: {
      delete: { kind: "mutation", path: "agent.credentials.delete" },
      get: { kind: "query", path: "agent.credentials.get" },
      list: { kind: "query", path: "agent.credentials.list" },
      save: { kind: "mutation", path: "agent.credentials.save" },
    },
    skills: {
      delete: { kind: "mutation", path: "agent.skills.delete" },
      get: { kind: "query", path: "agent.skills.get" },
      list: { kind: "query", path: "agent.skills.list" },
      upload: { kind: "mutation", path: "agent.skills.upload" },
    },
  },
  apiKeys: {
    create: { kind: "mutation", path: "apiKeys.create" },
    list: { kind: "query", path: "apiKeys.list" },
    revoke: { kind: "mutation", path: "apiKeys.revoke" },
  },
  auth: {
    login: { kind: "mutation", path: "auth.login" },
    logout: { kind: "mutation", path: "auth.logout" },
  },
  credentials: {
    delete: { kind: "mutation", path: "credentials.delete" },
    list: { kind: "query", path: "credentials.list" },
    save: { kind: "mutation", path: "credentials.save" },
  },
  skills: {
    delete: { kind: "mutation", path: "skills.delete" },
    list: { kind: "query", path: "skills.list" },
    save: { kind: "mutation", path: "skills.save" },
  },
} as const;

export const internal = api;
export type Api = typeof api;
