// Generated by gonvex dev. Do not edit.

export const api = {
  agent: {
    apiKeys: {
      list: { kind: "query", path: "agent.apiKeys.list" },
      revoke: { kind: "mutation", path: "agent.apiKeys.revoke" },
      revokeSelf: { kind: "mutation", path: "agent.apiKeys.revokeSelf" },
      verify: { kind: "query", path: "agent.apiKeys.verify" },
    },
    credentials: {
      delete: { kind: "mutation", path: "agent.credentials.delete" },
      get: { kind: "query", path: "agent.credentials.get" },
      list: { kind: "query", path: "agent.credentials.list" },
      save: { kind: "mutation", path: "agent.credentials.save" },
    },
    skills: {
      delete: { kind: "mutation", path: "agent.skills.delete" },
      get: { kind: "query", path: "agent.skills.get" },
      list: { kind: "query", path: "agent.skills.list" },
      upload: { kind: "mutation", path: "agent.skills.upload" },
    },
  },
  apiKeys: {
    create: { kind: "mutation", path: "apiKeys.create" },
    list: { kind: "query", path: "apiKeys.list" },
    revoke: { kind: "mutation", path: "apiKeys.revoke" },
  },
  auth: {
    login: { kind: "mutation", path: "auth.login" },
    logout: { kind: "mutation", path: "auth.logout" },
    me: { kind: "query", path: "auth.me" },
    switchWorkspace: { kind: "mutation", path: "auth.switchWorkspace" },
    workspaces: { kind: "query", path: "auth.workspaces" },
  },
  credentials: {
    delete: { kind: "mutation", path: "credentials.delete" },
    get: { kind: "mutation", path: "credentials.get" },
    list: { kind: "query", path: "credentials.list" },
    save: { kind: "mutation", path: "credentials.save" },
  },
  skills: {
    approve: { kind: "mutation", path: "skills.approve" },
    delete: { kind: "mutation", path: "skills.delete" },
    get: { kind: "query", path: "skills.get" },
    list: { kind: "query", path: "skills.list" },
    save: { kind: "mutation", path: "skills.save" },
  },
  team: {
    invitations: {
      accept: { kind: "mutation", path: "team.invitations.accept" },
      list: { kind: "query", path: "team.invitations.list" },
      reject: { kind: "mutation", path: "team.invitations.reject" },
    },
    invite: { kind: "mutation", path: "team.invite" },
    list: { kind: "query", path: "team.list" },
    remove: { kind: "mutation", path: "team.remove" },
  },
} as const;

export const internal = api;
export type Api = typeof api;
